settings:
  tileRange: 48
hiddenTiles:
  materials:
    - CHEST
    - BARREL
    - FURNACE
    - HOPPER
    - ENDER_CHEST
    - TRAPPED_CHEST
    - BLAST_FURNACE
    - CAMPFIRE
    - DISPENSER
    - DROPPER
    - BREWING_STAND
    - SPAWNER
    - ENCHANTING_TABLE
    - DRAGON_HEAD
    - DRAGON_WALL_HEAD
    - PLAYER_HEAD
    - PLAYER_WALL_HEAD
    - SUSPICIOUS_GRAVEL
    - SUSPICIOUS_SAND
    - SKELETON_SKULL
    - SKELETON_WALL_SKULL
    - WITHER_SKELETON_SKULL
    - WITHER_SKELETON_WALL_SKULL
    - ZOMBIE_HEAD
    - ZOMBIE_WALL_HEAD
    - CREEPER_HEAD
    - CREEPER_WALL_HEAD
  tags:
    - SHULKER_BOXES
    - ALL_SIGNS
    - BEDS
  # NMS keys (skull/banner/bed/brushable_block) are needed to hide some types of blocks when sending chunks to the client
  keys:
    - brushable_block
    - bed
    - skull
